# These are supported funding model platforms

github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [andripwn, pwn0sec]
patreon: # Replace with a single Patreon username
open_collective: # Replace with a single Open Collective pwn0sec
ko_fi: # Replace with a single Ko-fi pwn0sec
tidelift: # Replace with a single Tidelift platform-name/package-name e.g., npm/babel
community_bridge: # Replace with a single Community Bridge project-name e.g., cloud-foundry
liberapay: # Replace with a single Liberapay pwn0sec
issuehunt: # Replace with a single IssueHunt pwn0sec
otechie: # Replace with a single Otechie pwn0sec
custom: # Replace with up to 4 custom sponsorship URLs e.g., ['https://paypal.me/andripwn', 'https://paypal.me/andripwn']
